---

- hosts: all
  vars:
    packages:
      - git
      - php5-cli
      - php5-xdebug
    phars:
      composer: https://getcomposer.org/composer.phar
      phpunit:  https://phar.phpunit.de/phpunit.phar
      box:      https://github.com/box-project/box2/releases/download/2.6.0/box-2.6.0.phar
    php_ini:
      "default_charset": "UTF-8"
      "date.timezone":   "UTC"
  tasks:
    - apt_repository: repo="deb http://packages.dotdeb.org {{ ansible_distribution_release }}-php56 all" state=present
    - apt_key: url="http://www.dotdeb.org/dotdeb.gpg"
    - apt: name={{ item }} update_cache=yes state=latest
      with_items: packages
    - get_url: url={{ item.value }} dest=/usr/local/bin/{{ item.key }} mode=0755
      with_dict: phars
    - lineinfile: dest=/etc/php5/cli/php.ini regexp="^{{ item.key }}" line="{{ item.key }}={{ item.value }}" state=present
      with_dict: php_ini
